# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qdNn6OMEBCEiOMWZ98sen1Ocs_fDjvnS
"""

#import load_iris function from datasets module
from sklearn.datasets import load_iris

#Save "bunch" object containing iris dataset and its attributes
iris=load_iris()
type(iris)

#Print the iris data
print (iris.data)

#Print the names of the four features
print (iris.feature_names)

print(iris.target)

#Print the encoading scheme for species: 0=setosa, 1=versicolor, 2= virginica
print(iris.target_names)

#check the types of the features and response
print(type(iris.data))
print(type(iris.target))

print(iris.data.shape)

print(iris.target.shape)

#store feature matrix in "x"
X=iris.data
#store response vector in "y"
Y=iris.target